/* soapStub.h
   Generated by gSOAP 2.8.95 for calc.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#define SOAP_NAMESPACE_OF_ns2	"urn:calc"
#if 0
#endif

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20895
# error "GSOAP VERSION 20895 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Structs and Unions                                                         *
 *                                                                            *
\******************************************************************************/

typedef struct get_book get_book;	/* calc.h:282 */
struct ns2__addResponse;	/* calc.h:299 */
struct ns2__add;	/* calc.h:299 */
struct ns2__delResponse;	/* calc.h:357 */
struct ns2__del;	/* calc.h:357 */
struct ns2__modResponse;	/* calc.h:417 */
struct ns2__mod;	/* calc.h:417 */
struct ns2__inqResponse;	/* calc.h:474 */
struct ns2__inq;	/* calc.h:474 */
struct ns2__powResponse;	/* calc.h:534 */
struct ns2__pow;	/* calc.h:534 */

/* calc.h:282 */
#ifndef SOAP_TYPE_get_book
#define SOAP_TYPE_get_book (7)
/* complex XML schema type 'get-book': */
struct get_book {
        /** Optional element 'name' of XML schema type 'xsd:string' */
        char *name;
        /** Optional element 'kind' of XML schema type 'xsd:string' */
        char *kind;
        /** Optional element 'price' of XML schema type 'xsd:string' */
        char *price;
        /** Optional element 'time' of XML schema type 'xsd:string' */
        char *time;
};
#endif

/* calc.h:299 */
#ifndef SOAP_TYPE_ns2__addResponse
#define SOAP_TYPE_ns2__addResponse (10)
/* complex XML schema type 'ns2:addResponse': */
struct ns2__addResponse {
        /** Optional element 'result' of XML schema type 'xsd:string' */
        char **result;
};
#endif

/* calc.h:299 */
#ifndef SOAP_TYPE_ns2__add
#define SOAP_TYPE_ns2__add (11)
/* complex XML schema type 'ns2:add': */
struct ns2__add {
        /** Optional element 'bookname' of XML schema type 'xsd:string' */
        char *bookname;
        /** Optional element 'bookkind' of XML schema type 'xsd:string' */
        char *bookkind;
        /** Optional element 'bookprice' of XML schema type 'xsd:string' */
        char *bookprice;
};
#endif

/* calc.h:357 */
#ifndef SOAP_TYPE_ns2__delResponse
#define SOAP_TYPE_ns2__delResponse (13)
/* complex XML schema type 'ns2:delResponse': */
struct ns2__delResponse {
        /** Optional element 'result' of XML schema type 'xsd:string' */
        char **result;
};
#endif

/* calc.h:357 */
#ifndef SOAP_TYPE_ns2__del
#define SOAP_TYPE_ns2__del (14)
/* complex XML schema type 'ns2:del': */
struct ns2__del {
        /** Optional element 'bookname' of XML schema type 'xsd:string' */
        char *bookname;
};
#endif

/* calc.h:417 */
#ifndef SOAP_TYPE_ns2__modResponse
#define SOAP_TYPE_ns2__modResponse (16)
/* complex XML schema type 'ns2:modResponse': */
struct ns2__modResponse {
        /** Optional element 'result' of XML schema type 'xsd:string' */
        char **result;
};
#endif

/* calc.h:417 */
#ifndef SOAP_TYPE_ns2__mod
#define SOAP_TYPE_ns2__mod (17)
/* complex XML schema type 'ns2:mod': */
struct ns2__mod {
        /** Required element 'hashvalue' of XML schema type 'xsd:int' */
        int hashvalue;
        /** Optional element 'mod-name' of XML schema type 'xsd:string' */
        char *mod_name;
        /** Optional element 'mod-later-name' of XML schema type 'xsd:string' */
        char *mod_later_name;
};
#endif

/* calc.h:474 */
#ifndef SOAP_TYPE_ns2__inqResponse
#define SOAP_TYPE_ns2__inqResponse (19)
/* complex XML schema type 'ns2:inqResponse': */
struct ns2__inqResponse {
        /** Optional element 'result' of XML schema type 'xsd:string' */
        char **result;
};
#endif

/* calc.h:474 */
#ifndef SOAP_TYPE_ns2__inq
#define SOAP_TYPE_ns2__inq (20)
/* complex XML schema type 'ns2:inq': */
struct ns2__inq {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* calc.h:534 */
#ifndef SOAP_TYPE_ns2__powResponse
#define SOAP_TYPE_ns2__powResponse (24)
/* complex XML schema type 'ns2:powResponse': */
struct ns2__powResponse {
        /** Optional element 'result' of XML schema type 'xsd:double' */
        double *result;
};
#endif

/* calc.h:534 */
#ifndef SOAP_TYPE_ns2__pow
#define SOAP_TYPE_ns2__pow (25)
/* complex XML schema type 'ns2:pow': */
struct ns2__pow {
        /** Required element 'a' of XML schema type 'xsd:double' */
        double a;
        /** Required element 'b' of XML schema type 'xsd:double' */
        double b;
};
#endif

/* calc.h:595 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (26)
/* SOAP_ENV__Header: */
struct SOAP_ENV__Header {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif
#endif

/* calc.h:595 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (27)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_ENV__Code {
        /** Optional element 'SOAP-ENV:Value' of XML schema type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
};
#endif
#endif

/* calc.h:595 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (29)
/* SOAP_ENV__Detail: */
struct SOAP_ENV__Detail {
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_<typename> assigned to __type */
        /** Do not create a cyclic data structure through this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
};
#endif
#endif

/* calc.h:595 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (32)
/* SOAP_ENV__Reason: */
struct SOAP_ENV__Reason {
        /** Optional element 'SOAP-ENV:Text' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Text;
};
#endif
#endif

/* calc.h:595 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (33)
/* SOAP_ENV__Fault: */
struct SOAP_ENV__Fault {
        /** Optional element 'faultcode' of XML schema type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XML schema type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XML schema type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XML schema type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* double has binding name 'double' for type 'xsd:double' */
#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (21)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (33)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (32)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (29)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (27)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (26)
#endif

/* struct ns2__pow has binding name 'ns2__pow' for type 'ns2:pow' */
#ifndef SOAP_TYPE_ns2__pow
#define SOAP_TYPE_ns2__pow (25)
#endif

/* struct ns2__powResponse has binding name 'ns2__powResponse' for type 'ns2:powResponse' */
#ifndef SOAP_TYPE_ns2__powResponse
#define SOAP_TYPE_ns2__powResponse (24)
#endif

/* struct ns2__inq has binding name 'ns2__inq' for type 'ns2:inq' */
#ifndef SOAP_TYPE_ns2__inq
#define SOAP_TYPE_ns2__inq (20)
#endif

/* struct ns2__inqResponse has binding name 'ns2__inqResponse' for type 'ns2:inqResponse' */
#ifndef SOAP_TYPE_ns2__inqResponse
#define SOAP_TYPE_ns2__inqResponse (19)
#endif

/* struct ns2__mod has binding name 'ns2__mod' for type 'ns2:mod' */
#ifndef SOAP_TYPE_ns2__mod
#define SOAP_TYPE_ns2__mod (17)
#endif

/* struct ns2__modResponse has binding name 'ns2__modResponse' for type 'ns2:modResponse' */
#ifndef SOAP_TYPE_ns2__modResponse
#define SOAP_TYPE_ns2__modResponse (16)
#endif

/* struct ns2__del has binding name 'ns2__del' for type 'ns2:del' */
#ifndef SOAP_TYPE_ns2__del
#define SOAP_TYPE_ns2__del (14)
#endif

/* struct ns2__delResponse has binding name 'ns2__delResponse' for type 'ns2:delResponse' */
#ifndef SOAP_TYPE_ns2__delResponse
#define SOAP_TYPE_ns2__delResponse (13)
#endif

/* struct ns2__add has binding name 'ns2__add' for type 'ns2:add' */
#ifndef SOAP_TYPE_ns2__add
#define SOAP_TYPE_ns2__add (11)
#endif

/* struct ns2__addResponse has binding name 'ns2__addResponse' for type 'ns2:addResponse' */
#ifndef SOAP_TYPE_ns2__addResponse
#define SOAP_TYPE_ns2__addResponse (10)
#endif

/* struct get_book has binding name 'get_book' for type 'get-book' */
#ifndef SOAP_TYPE_get_book
#define SOAP_TYPE_get_book (7)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (35)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (34)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (28)
#endif

/* double * has binding name 'PointerTodouble' for type 'xsd:double' */
#ifndef SOAP_TYPE_PointerTodouble
#define SOAP_TYPE_PointerTodouble (22)
#endif

/* char ** has binding name 'PointerTostring' for type 'xsd:string' */
#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (8)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    
    /** Web service synchronous operation 'soap_call_ns2__add' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__add(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *bookname, char *bookkind, char *bookprice, char **result);
    /** Web service asynchronous operation 'soap_send_ns2__add' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns2__add(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *bookname, char *bookkind, char *bookprice);
    /** Web service asynchronous operation 'soap_recv_ns2__add' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns2__add(struct soap *soap, char **result);
    
    /** Web service synchronous operation 'soap_call_ns2__del' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__del(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *bookname, char **result);
    /** Web service asynchronous operation 'soap_send_ns2__del' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns2__del(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *bookname);
    /** Web service asynchronous operation 'soap_recv_ns2__del' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns2__del(struct soap *soap, char **result);
    
    /** Web service synchronous operation 'soap_call_ns2__mod' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__mod(struct soap *soap, const char *soap_endpoint, const char *soap_action, int hashvalue, char *mod_name, char *mod_later_name, char **result);
    /** Web service asynchronous operation 'soap_send_ns2__mod' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns2__mod(struct soap *soap, const char *soap_endpoint, const char *soap_action, int hashvalue, char *mod_name, char *mod_later_name);
    /** Web service asynchronous operation 'soap_recv_ns2__mod' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns2__mod(struct soap *soap, char **result);
    
    /** Web service synchronous operation 'soap_call_ns2__inq' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__inq(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **result);
    /** Web service asynchronous operation 'soap_send_ns2__inq' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns2__inq(struct soap *soap, const char *soap_endpoint, const char *soap_action);
    /** Web service asynchronous operation 'soap_recv_ns2__inq' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns2__inq(struct soap *soap, char **result);
    
    /** Web service synchronous operation 'soap_call_ns2__pow' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__pow(struct soap *soap, const char *soap_endpoint, const char *soap_action, double a, double b, double *result);
    /** Web service asynchronous operation 'soap_send_ns2__pow' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns2__pow(struct soap *soap, const char *soap_endpoint, const char *soap_action, double a, double b);
    /** Web service asynchronous operation 'soap_recv_ns2__pow' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns2__pow(struct soap *soap, double *result);

#endif

/* End of soapStub.h */
